# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org  (for organization related metrics)
          #  - read:user (for user related data)
          #  - repo      (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: plainde
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Moscow
          plugin_lines: yes
          plugin_pagespeed: yes
          plugin_pagespeed_url: https://plainde.org
          plugin_rss: yes
          plugin_rss_limit: 8
          plugin_rss_source: https://plainde.org/feed.xml
